import React from 'react'
import '../Style/user.css'
import UserToken from './UserToken'
import Button from 'react-bootstrap/Button';



function User() {
  return (
    <div className='user'>
      <h1>User Form</h1>
      <Button variant="primary" id="logout">Logout</Button>
        <form action="" className="user-form">
            
            <div id="grp1">
            <label htmlFor="date">Date:</label>
            <input type="date" id="date" name="date" required/>
            <br/>
            <label htmlFor="machine_name">Machine Name:</label>
            <input type="text" id="machine_name" name="machine_name" required/>
            <br/>
            <label htmlFor="customer_name">Customer Name:</label>
            <input type="text" id="customer_name" name="customer_name" required/>
            <br/>
            <label htmlFor="problem">Problem Reported By:</label>
            <input type="text" id="problem" name="problem" required/>
            <br/>
            </div>
            <div id="grp2">
            <label htmlFor="created_by">Token Generated By:</label>
            <input type="text" id="created_by" name="created_by" required/>
            <br/>
            <label htmlFor="desc">Problem Description:</label>
            <textarea id="desc" name="desc"></textarea>
            <br/>
            <label htmlFor="image">Upload Image:</label>
            <input type="file" id="image" name="image"/>
            <br/>
            </div>
            
        </form>
        <div className="user-btn">
           <Button variant="success"  type='submit'>Submit</Button>
            <Button variant="success" type='reset'>Reset</Button>
            {/* <button type='submit'>Submit</button>
            <button type='reset'>Reset</button> */}
        </div>
       <hr className="divider" />
        <div className="token-info">
            <h2>Token Information</h2>
            <UserToken date="2023-10-01" machine_name="Mark II" customer_name="Balaji India Pvt Ltd, Delhi" problem="Rajeev Rana" created_by="Sanjay Ramawat" desc="WP can not exceed above 15" status="Pending" image="https://images.unsplash.com/photo-1471890701797-59336a877de4?q=80&w=1465&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />
        </div>
    </div>
  )
}

export default User