import React from 'react'

function User() {
  return (
    <div>
        <form action="" className="user-form">
            <h1>User Form</h1>
            <label htmlFor="date">Date:</label>
            <input type="date" id="date" name="date" required/>
            <br/>
            <label htmlFor="machine_name">Machine Name:</label>
            <input type="text" id="machine_name" name="machine_name" required/>
            <br/>
            <label htmlFor="customer_name">Customer Name:</label>
            <input type="text" id="customer_name" name="customer_name" required/>
            <br/>
            <label htmlFor="problem">Problem Reported By:</label>
            <input type="text" id="problem" name="problem" required/>
            <br/>
            <label htmlFor="created_by">Token Generated By:</label>
            <input type="text" id="created_by" name="created_by" required/>
            <br/>
            <label htmlFor="desc">Problem Description:</label>
            <textarea id="desc" name="desc"></textarea>
            <br/>
            <label htmlFor="image">Upload Image:</label>
            <input type="file" id="image" name="image"/>
            <br/>
            <button type='submit'>Submit</button>
            <button type='reset'>Reset</button>
        </form>
        <div className="token-info">
            <h2>Token Information</h2>
        </div>
    </div>
  )
}

export default User